### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by adeline0618** [adeline0618/-Pre-Project-U2#1]
### 만들고자 하는 기능이 무엇인가요?
Todo 생성
Todo 삭제
Todo 수정
Todo 확인

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] Todo 생성 컴포넌트 만들기
2.  [ ] Todo 보여주기 컴포넌트 만들기
3. [ ] Todo 삭제 컴포넌트 만들기
4. [ ] Todo 수정 컴포넌트 만들기
5. [ ] App Style 편집

### 예상 작업시간 
5h
