### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by adeline0618** [adeline0618/-Pre-Project-U2#2]
### 만들고자 하는 기능
Todo 생성, 확인, 삭제, 수정

### 해당 기능을 구현하기 위해 할 일
1. [ ] Todo 생성 컴포넌트 만들기.
2. [ ] Todo 확인 컴포넌트 만들기.
3. [ ] Todo 삭제 컴포넌트 만들기.
4. [ ] Todo 수정 컴포넌트 만들기.
5. [ ] App Style 설정

### 예상 작업 시간
5h
